translate app models and basic structure
Cadovvl/trainer pull request #36
Opened 2020-09-08 11:37 UTC by PavelYasukevich

Добавлено приложение для перевода слов. (название надо бы придумать получше, чтобы не сильно перекликалось с существующим translates).
Добавлены модели для вопроса и состоящего из вопросов задания, привязанного к пользователю (ожидается мерж юзер модели)
добавлены заготовки структуры (view, template, url)

2020-09-08 16:32 UTC, Cadovvl commented
Тесты сюда хочу!

2020-09-09 14:07 UTC, PavelYasukevich commented
Я думаю генератор заданий сначала написать, и уже вместе с ним можно тесты запилить.

2020-09-09 16:00 UTC, Cadovvl commented
Хозяин-барин

2020-09-09 16:05 UTC, Cadovvl requested changes

2020-09-09 16:05 UTC, Cadovvl commented on translate_app/models.py
> +    answer_options = models.JSONField()
Плохо. 

Лучше поставить ссылки на Word. А лучше, чтобы была отдельная таблица с вариантами ответа, которая ссылается на вопрос.

2020-09-09 16:05 UTC, Cadovvl commented on translate_app/models.py
> +        help_text="Задание, содержащее слово"
Содержащее вопрос(question)? 

Вообще, надо гдe-то зафиксировать терминологию.

2020-09-10 06:39 UTC, PavelYasukevich commented on translate_app/models.py
> +    answer_options = models.JSONField()
Ну вообще идея была в генераторе заданий обращаться к Word, доставать переревод, и с еще 3мя рандомными переводами записывать в это поле. Примерно так :
{"options": [ {"option1": translation1, "correct": True], {"option2": translation2, "correct": False}, ... ] }

2020-09-10 10:21 UTC, Cadovvl commented on translate_app/models.py
> +    answer_options = models.JSONField()
Нет, нет, нет. 

Раз уж используем реляционную БД, пользуемся всеми ее преимуществами. 

Вот скажи, что ты будешь делать, если в какой-то момент в поле запишется неправильный ключ? Мы сломаемся в продакшене прежде чем узнаем о проблеме? 
Что если мы захотим убрать отовсюду слово (непример, неприличное), как ты его вырезать отсюда собрался? 


Только через схему БД, фантазируй. Намек, как сделать, я дал выше.

2020-09-10 18:48 UTC, AnnnnaS commented on templates/main_screen.html
>          <div class="card-group">
Это мой первый комментарий, ура. А не перенести ли нам шаблоны главного экрана в папку screen/templates? Или screen - не приложение. а главная страница? (рубрика - занудство :) )

2020-09-10 19:24 UTC, Cadovvl commented on templates/main_screen.html
>          <div class="card-group">
screen - приложение. Но я бы туда шаблоны не бросал - есть ряд переиспользуемых. 

А вот навести порядок внутри папки templates - можно. Разбить шаблоны на подпапки common, screen, translate, gallow. 

Создай на это дело issue, и зарезолвь комментарий к этому ревью: это чуть больше оффтоп.

2020-09-11 13:42 UTC, Cadovvl requested changes

2020-09-11 13:42 UTC, Cadovvl commented on translate_app/models.py
> +    bait_1 = models.CharField(max_length=20)
А как ты в такой схеме решишь следующу. задачу: на некоторые вопросы ты хочешь 5 вариантов ответа, на некоторые три?

И у тебя слово, а должна быть ссылка на таблицу Words.

2020-09-11 14:18 UTC, PavelYasukevich commented on translate_app/models.py
> +    bait_1 = models.CharField(max_length=20)
В ТЗ речь шла о выборе из 4х вариантов же. Но это мелочи, можно и переменным сделать.
 А вот насчет сыылки на Вордс - мы точно хотим в таблицу вордс эти связи? В приложении Gallows, например, специально не стали этого делать.

2020-09-11 17:51 UTC, Cadovvl commented on translate_app/models.py
> +    bait_1 = models.CharField(max_length=20)
Ну тут та же проблема, что и везде: а если мы захотим удалить слово? Забанили в словаре слов "коммунизм". Мы по всем приложенькам будем бегать и его вырезать? 

Пусть наш список слов хранится в одном месте - будет универсальность. 
Про четыре варианта ответа - пусть будет 4 варианта. Никаких проблем.

2020-09-12 09:01 UTC, Cadovvl approved these changes

2020-09-14 20:10 UTC, Cadovvl requested changes

2020-09-14 20:10 UTC, Cadovvl commented on translate_app/views.py
> +            Word.objects.filter(lang=word_lang).exclude(word__in=used_words)
Ты бы хоть ограничение по количеству поставил. Он же у тебя всю базу в память загрузит

2020-09-14 20:10 UTC, Cadovvl commented on translate_app/models.py
> +        Word, on_delete=models.CASCADE, related_name="+"
Плохое имя. Совпадает с оператором: неудобно для генератора.

2020-09-14 20:10 UTC, Cadovvl commented on translate_app/tests/fixtures/fixture_data.py
> +    translations = Translation.objects.bulk_create(
Зачем тебе 5 слов если всего два перевода?

2020-09-14 20:10 UTC, Cadovvl commented on translate_app/views.py
> +            Word.objects.filter(lang=word_lang).exclude(word__in=used_words)
Кстати, ты правда бедушь на каждом шаге цикла ходить в базу? Тоесть на 10 заданий у тебя будет 30 запросов? Мы не задохнемся?

2020-09-14 20:10 UTC, Cadovvl commented on translate_app/views.py
> +        question = Question.objects.create(task=new_task, word=word_to_guess)
Сделай объекты, а для них bulk_create

2020-09-15 06:30 UTC, PavelYasukevich commented on translate_app/models.py
> +        Word, on_delete=models.CASCADE, related_name="+"
[https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.ForeignKey.related_name](url)
Тут сказали, что таким образом поле связи не будет создано.

2020-09-15 06:31 UTC, PavelYasukevich commented on translate_app/tests/fixtures/fixture_data.py
> +    translations = Translation.objects.bulk_create(
Чтобы было из чего выбрать неверные опции.

2020-09-15 06:34 UTC, Cadovvl commented on translate_app/models.py
> +        Word, on_delete=models.CASCADE, related_name="+"
Пардоньте, не знал. Тогда нет претензий

2020-09-15 06:34 UTC, Cadovvl commented on translate_app/models.py
> +        Word, on_delete=models.CASCADE, related_name="+"
Блин, клевая фича!!

2020-09-15 08:24 UTC, PavelYasukevich commented on translate_app/views.py
> +        question = Question.objects.create(task=new_task, word=word_to_guess)
Question можно сделать скопом, но как быть с их AnswerOptions? Им нужно указывать соответсвующий Question, а на этапе объектов они не привязываются.

2020-09-17 08:25 UTC, Cadovvl requested changes

2020-09-17 08:25 UTC, Cadovvl commented on translate_app/views.py
> +        question = Question.objects.create(task=new_task, word=word_to_guess)
Первое и главное - зачем у тебя AnswerOptions уехало от задания? В твоей текущей схеме получается, что для твоего текущего "Вопроса" (Пары id сессии и слова) может быть несколько вариантов ответов. Но это не так: внутри одной сессии (это сессия для одного пользователя) есть только одно задание на это слово с единственным набором вариантов ответа.

2020-09-17 08:25 UTC, Cadovvl commented on translate_app/views.py
> +            translation.source_word.word, translation_lang
Каждый вызов translations - запрос в базу данных.

2020-09-17 08:25 UTC, Cadovvl commented on translate_app/views.py
> +            ).values_list("id", flat=True)
Я бы, кстати, id слов закешировал. Но это не в этом ревью, а на будущее.

2020-09-17 08:25 UTC, Cadovvl commented on translate_app/views.py
> +    new_task = Task.objects.create(user=user)
Надо все это засунуть в "транзакцию", чтобы процесс не оборвался на середине. Либо в базу будет записано все, либо ничего.

2020-09-17 13:03 UTC, PavelYasukevich commented on translate_app/views.py
> +    new_task = Task.objects.create(user=user)
Понял, сделаю

2020-09-17 13:04 UTC, PavelYasukevich commented on translate_app/views.py
> +            translation.source_word.word, translation_lang
А слона-то я и не заметил(

2020-09-17 13:11 UTC, PavelYasukevich commented on translate_app/views.py
> +        question = Question.objects.create(task=new_task, word=word_to_guess)
Я это кстати поправил в ветке с вьюхами, поменял на один-к-одному в модели. Об этом же речь?
Перенесу тогда сюда эти изменения.
Это все еще имеет отношение к bulk_create ?

2020-09-17 13:30 UTC, PavelYasukevich commented on translate_app/views.py
> +            translation.source_word.word, translation_lang
Хотя с другой стороны - а что поделать? Для каждого Вопроса надо исключать все его переводы из вариантов, функция у тебя ничего лишнего из бд не тащит. Предлагаешь ею не пользоваться и перед циклом как-то в один заход эти переводы вытягивать?
Думаю.

2020-09-17 13:59 UTC, PavelYasukevich commented on translate_app/views.py
> +            translation.source_word.word, translation_lang
Вроде придумал, но тесты упали, работаю.

2020-09-17 14:09 UTC, Cadovvl commented on translate_app/views.py
> +        question = Question.objects.create(task=new_task, word=word_to_guess)
так проще сделать bulk_create

2020-09-17 14:11 UTC, Cadovvl commented on translate_app/models.py
> +    question = models.OneToOneField(
Ну все-равно не понимаю, на кой тебе две модели делать.

2020-09-17 14:16 UTC, Cadovvl approved these changes

2020-09-18 02:54 UTC, PavelYasukevich commented on translate_app/models.py
> +    question = models.OneToOneField(
А, вот ты о чем. Ну вообще да, можно объединить, тогда и создавать можно будет группой. Сделаю в следующем релизе =)

2020-09-19 11:41 UTC, cement-hools approved these changes

2020-09-19 12:48 UTC, merged