Terrible button
Cadovvl/trainer pull request #39
Opened 2020-09-14 20:09 UTC by AnnnnaS

Add a new terrible button in start screen of Pavel's game

2020-09-14 20:16 UTC, Cadovvl requested changes

2020-09-14 20:16 UTC, Cadovvl commented on gallows/templates/gallows/gallows_start.html
> +           <style>
Все стили должны быть в css файлах

2020-09-14 20:16 UTC, Cadovvl commented on gallows/templates/gallows/gallows_start.html
> +            .button {
Это имя класса сломает все кнопки. Задай уникальное имя для стиля.

2020-09-14 20:16 UTC, Cadovvl commented on gallows/templates/gallows/gallows_start.html
> +            0% { background-color: #a81805; box-shadow: 0 0 5px #a81805; }
Форматирование, отступы!! ___*( ￣皿￣)/#____

2020-09-14 20:16 UTC, Cadovvl commented on gallows/templates/gallows/gallows_start.html
> -          <div class="col-md-8">
открывающий див ты убрала, а закрывающий оставила. Надо думать, ты приложеньку не запускала, потому что у тебя эта страница, скорее всего просто не отобразится, а если и отобразится, то превратится в свалку.

2020-09-15 04:39 UTC, PavelYasukevich approved these changes
Кроме замечаний Павла добавить нечего. Кнопка - огонь!

2020-09-16 18:42 UTC, closed without merging

2020-09-17 15:59 UTC, denis-student commented
well done!