Red button. Again
Cadovvl/trainer pull request #43
Opened 2020-09-16 18:42 UTC by AnnnnaS

Я не поняла, как добавить изменения в прежний ПР и поэтому сделала новый, пардоньте. Зато - из консоли, а не через позорное редактирование файлов на сайте гитхаба.

2020-09-16 18:45 UTC, Cadovvl commented
Добавлять легко: делаешь коммит в эту же ветку из консоли и делаешь 
`git push origin <имяветки>`

2020-09-16 18:47 UTC, Cadovvl requested changes

2020-09-16 18:47 UTC, Cadovvl commented on templates/main_screen.html
> +        <html>
Откуда и зачем это взялось? Где закрывающий тег?

2020-09-16 18:47 UTC, Cadovvl commented on gallows/templates/gallows/gallows_start.html
> +          <div>
А можешь диву класс назад вернуть? он отступы делает....

2020-09-17 03:14 UTC, PavelYasukevich approved these changes

2020-09-17 07:26 UTC, Cadovvl approved these changes

2020-09-17 17:40 UTC, merged