href to home page
Cadovvl/trainer pull request #47
Opened 2020-09-19 19:21 UTC by AnnnnaS

Теперь по клику на логотип в левом верхнем углу возвращается стартовая страница. Но туда же ведет и кнопка 'Home'. Может, убрать тогда ссылку с логотипа? Или убрать кнопку home

2020-09-19 21:29 UTC, Cadovvl requested changes

2020-09-19 21:29 UTC, Cadovvl commented on templates/header.html
> +  <a class="navbar-brand" href="/">Language Trainer</a>
Тогда может тоже сделать `{{ main_page }}` ?

2020-09-20 00:52 UTC, cement-hools commented on templates/header.html
> +  <a class="navbar-brand" href="/">Language Trainer</a>
Уже замерджил с ссылкой на главную? Или тут что-то другое?

2020-09-20 08:53 UTC, Cadovvl commented on templates/header.html
> +  <a class="navbar-brand" href="/">Language Trainer</a>
Я подумал, что не везде. Но сейчас проверил - да, ты прав, там же. 

@AnnnnaS , проверь, у тебя к этому PR должна быть вкладка conflicts, где будет сказано, что ты пытаешься поменять файл, который уже изменен в мастере.

2020-09-23 19:03 UTC, closed without merging